export type Kol = {
  id: string;
  handle: string;
  name: string;
  ticker: string;
  wallet: string;
  image: string;
  x: string;
  avatar: string;
  price: number;
  change24h: number;
  marketCap: number;
  volume24h: number;
  holders: number;
  winRate: number;
  pnl30d: number;
  trades30d: number;
  avgHold: string;
  chain: string;
  bio: string;
};

type Seed = {
  id: string;
  name: string;
  ticker: string;
  wallet: string;
  image: string;
  x: string;
  handle: string;
  hue: number;
};

/**
 * Traders listed on SHARPS: four hand-picked from the operator's Axiom
 * wallet tracker (first below), then the Solana KOL leaderboard from Axiom's Trackers
 * page (its FOMO and Pump App smart-money lists), captured 2026-09-29 —
 * every entry has a wallet the source marks as verified. Traded on our own
 * program (anchor/programs/sharps). Every listing opens at the same price;
 * all divergence is earned by on-chain performance after launch.
 *
 * Identity (name / handle / avatar) is the source's own profile data. Only
 * traders who linked an X account get an X link; the rest show their FOMO or
 * Pump handle — deliberately not guessed, since attributing the wrong X
 * account to a real trader is worse than showing none.
 *
 * `id` is the wallet's first 6 characters (longer only if two collide), and
 * `ticker` is unique per listing — duplicates get a numeric suffix, because
 * two listings both showing the same ticker is unreadable on a trading screen.
 *
 * AVATARS: an X avatar via unavatar.io where there is an X handle, otherwise
 * the source's hosted picture. Third-party either way; AvatarMark falls back
 * to the ticker letters if a load fails, so an outage degrades rather than
 * breaks.
 */
const SEEDS: Seed[] = [
  // Hand-picked from the operator's own Axiom wallet tracker. X handles and
  // pictures come from kolscan.io or Axiom's KOL list, which lists each of these wallets (for Pow,
  // his kolscan-listed wallet 8zFZ…; this is his active one). Blank where no
  // public source ties the wallet to an X account — not guessed.
  {
    id: "3BLjRc",
    name: "Sebastian (Pablo)",
    ticker: "PABLO",
    wallet: "3BLjRcxWGtR7WRshJ3hL25U3RjWr5Ud98wMcczQqk4Ei",
    image: "https://cdn.kolscan.io/profiles/3BLjRcxWGtR7WRshJ3hL25U3RjWr5Ud98wMcczQqk4Ei.png",
    x: "https://x.com/Saint_pablo123",
    handle: "@Saint_pablo123",
    hue: 246,
  },
  {
    id: "VJSDW6",
    name: "Beanz",
    ticker: "BEANZ",
    wallet: "VJSDW6S74YXR4rRR9P4xwhMvLZJQMhrUb8XMFirUsy1",
    image: "https://unavatar.io/x/BeanzzSOL",
    x: "https://x.com/BeanzzSOL",
    handle: "@BeanzzSOL",
    hue: 277,
  },
  {
    id: "J23qr9",
    name: "Gr3g",
    ticker: "GR3G",
    wallet: "J23qr98GjGJJqKq9CBEnyRhHbmkaVxtTJNNxKu597wsA",
    image: "https://cdn.kolscan.io/profiles/J23qr98GjGJJqKq9CBEnyRhHbmkaVxtTJNNxKu597wsA.png",
    x: "https://x.com/gr3gor14n",
    handle: "@gr3gor14n",
    hue: 273,
  },
  {
    id: "8rvAsD",
    name: "Casino",
    ticker: "CASINO",
    wallet: "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR",
    image: "https://cdn.kolscan.io/profiles/8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR.png",
    x: "https://x.com/casino616",
    handle: "@casino616",
    hue: 168,
  },
  {
    id: "6ZhJwt",
    name: "TJR",
    ticker: "TJR",
    wallet: "6ZhJwthNyk4Qu7Cf3ymp9TSBcp8h1ZNMdfeD7LzsQmAB",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/479d82dd555343b24751b77df8cc219d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "https://x.com/_TJRTrades",
    handle: "@_TJRTrades",
    hue: 9,
  },
  {
    id: "9CNyLE",
    name: "rasmr",
    ticker: "RASMR",
    wallet: "9CNyLECt2j8tnDhqxtjYk5HUhZ2b8Nwnyb7sfYN7vND2",
    image: "https://unavatar.io/x/Rasmr_eth",
    x: "https://x.com/Rasmr_eth",
    handle: "@Rasmr_eth",
    hue: 74,
  },
  {
    id: "4UwK5A",
    name: "CottagePvP",
    ticker: "COTTGE",
    wallet: "4UwK5AE6Djdf3MfwtPGE8pFYD47MhU9fiStDVmSHJVMB",
    image: "https://unavatar.io/x/CottagePvP",
    x: "https://x.com/CottagePvP",
    handle: "@CottagePvP",
    hue: 345,
  },
  {
    id: "BQVz7f",
    name: "Limfork.eth",
    ticker: "LIMFRK",
    wallet: "BQVz7fQ1WsQmSTMY3umdPEPPTm1sdcBcX9sP7o6kPRmB",
    image: "https://cdn.kolscan.io/profiles/BQVz7fQ1WsQmSTMY3umdPEPPTm1sdcBcX9sP7o6kPRmB.png",
    x: "https://x.com/Limfork",
    handle: "@Limfork",
    hue: 58,
  },
  {
    id: "GZVSEA",
    name: "Washy",
    ticker: "WASHY",
    wallet: "GZVSEAajExLJEvACHHQcujBw7nJq98GWUEZtood9LM9b",
    image: "",
    x: "",
    handle: "",
    hue: 67,
  },
  {
    id: "Hw5UKB",
    name: "Trenchman",
    ticker: "TRENCH",
    wallet: "Hw5UKBU5k3YudnGwaykj5E8cYUidNMPuEewRRar5Xoc7",
    image: "https://cdn.kolscan.io/profiles/Hw5UKBU5k3YudnGwaykj5E8cYUidNMPuEewRRar5Xoc7.png",
    x: "https://x.com/trenchmanjames",
    handle: "@trenchmanjames",
    hue: 161,
  },
  {
    id: "DYAn4X",
    name: "The Doc",
    ticker: "DOC",
    wallet: "DYAn4XpAkN5mhiXkRB7dGq4Jadnx6XYgu8L5b3WGhbrt",
    image: "https://cdn.kolscan.io/profiles/DYAn4XpAkN5mhiXkRB7dGq4Jadnx6XYgu8L5b3WGhbrt.png",
    x: "https://x.com/KayTheDoc",
    handle: "@KayTheDoc",
    hue: 305,
  },
  {
    id: "CUHBzS",
    name: "samsrep",
    ticker: "SAMS",
    wallet: "CUHBzSPSaNS3tArEtM3maSV6pNdJhHJFYZpurPPK9P7H",
    image: "https://cdn.kolscan.io/profiles/CUHBzSPSaNS3tArEtM3maSV6pNdJhHJFYZpurPPK9P7H.png",
    x: "https://x.com/samsrepx",
    handle: "@samsrepx",
    hue: 289,
  },
  {
    id: "5YRgrP",
    name: "slingoor",
    ticker: "SLING",
    wallet: "5YRgrP3mjGzrzirYYN5HAQH19cTYREYwGxW6XRJQUzij",
    image: "https://cdn.kolscan.io/profiles/5YRgrP3mjGzrzirYYN5HAQH19cTYREYwGxW6XRJQUzij.png",
    x: "https://x.com/slingoorio",
    handle: "@slingoorio",
    hue: 156,
  },
  {
    id: "4sAUSQ",
    name: "Scharo",
    ticker: "SCHARO",
    wallet: "4sAUSQFdvWRBxR8UoLBYbw8CcXuwXWxnN8pXa4mtm5nU",
    image: "https://cdn.kolscan.io/profiles/4sAUSQFdvWRBxR8UoLBYbw8CcXuwXWxnN8pXa4mtm5nU.png",
    x: "https://x.com/XScharo",
    handle: "@XScharo",
    hue: 202,
  },
  {
    id: "Fvkc2t",
    name: "Brez",
    ticker: "BREZ",
    wallet: "Fvkc2thk1YcAASdR2gi8uf9n67JW9Dqqr9iRd99MDhoB",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/9caa5fbe9df82529474b068006cf0c94_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "https://x.com/brezscales",
    handle: "@brezscales",
    hue: 62,
  },
  {
    id: "7eNRAL",
    name: "Pow",
    ticker: "POW",
    wallet: "7eNRALuXYUJkUWTvRj5tcB7tcT43kmT5SNdkfy9fKTto",
    image: "https://cdn.kolscan.io/profiles/8zFZHuSRuDpuAR7J6FzwyF3vKNx4CVW3DFHJerQhc7Zd.png",
    x: "https://x.com/traderpow",
    handle: "@traderpow",
    hue: 109,
  },
  {
    id: "DuQabF",
    name: "orangie",
    ticker: "ORNGIE",
    wallet: "DuQabFqdC9eeBULVa7TTdZYxe8vK8ct5DZr4Xcf7docy",
    image: "https://cdn.kolscan.io/profiles/DuQabFqdC9eeBULVa7TTdZYxe8vK8ct5DZr4Xcf7docy.png",
    x: "https://x.com/orangie",
    handle: "@orangie",
    hue: 335,
  },
  {
    id: "8deJ9x",
    name: "Cooker",
    ticker: "COOKER",
    wallet: "8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6",
    image: "https://cdn.kolscan.io/profiles/8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6.png",
    x: "https://x.com/CookerFlips",
    handle: "@CookerFlips",
    hue: 144,
  },
  {
    id: "GfXQes",
    name: "Spuno",
    ticker: "SPUNO",
    wallet: "GfXQesPe3Zuwg8JhAt6Cg8euJDTVx751enp9EQQmhzPH",
    image: "https://cdn.kolscan.io/profiles/GfXQesPe3Zuwg8JhAt6Cg8euJDTVx751enp9EQQmhzPH.png",
    x: "https://x.com/spunosounds",
    handle: "@spunosounds",
    hue: 39,
  },
  {
    id: "86AEJE",
    name: "Publix",
    ticker: "PUBLIX",
    wallet: "86AEJExyjeNNgcp7GrAvCXTDicf5aGWgoERbXFiG1EdD",
    image: "https://cdn.kolscan.io/profiles/86AEJExyjeNNgcp7GrAvCXTDicf5aGWgoERbXFiG1EdD.png",
    x: "https://x.com/Publixplayz",
    handle: "@Publixplayz",
    hue: 342,
  },
  // Axiom Trackers → KOLs leaderboard.
  {
    id: "8xL8S7",
    name: "Avast",
    ticker: "AVAST",
    wallet: "8xL8S7P4QLdTGRquHas8NP5EVjp2qUGbmSgrkh97mvmq",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/a1d03f95749bb2c2150d9c682f5fe90b_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xAvast",
    hue: 44,
  },
  {
    id: "AGdtsM",
    name: "ExactTallTakin",
    ticker: "EXACTT",
    wallet: "AGdtsMmphhymH5wYW3dWKSkAxpLYRrNDCTFAfuq8ii9v",
    image: "",
    x: "",
    handle: "@ExactTallTakin",
    hue: 29,
  },
  {
    id: "U5Phnh",
    name: "LA",
    ticker: "LA",
    wallet: "U5PhnhckY1BB2hYoqTsbRf4MpUrnozVPemX3TAjDqaE",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d8ad002368c73112be3131a7a4a324dd_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@LA50197934",
    hue: 320,
  },
  {
    id: "AH75Bn",
    name: "bystevenr",
    ticker: "BYSTEV",
    wallet: "AH75Bn6QHSt5K2Ad4p1otns3JTwpSJWZTwiwKWNhmnKx",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/741f61cdb761b8b9465477fe6f22bb64_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@bystevenr",
    hue: 344,
  },
  {
    id: "Dqe1QK",
    name: "exitliqexe",
    ticker: "EXITLI",
    wallet: "Dqe1QKehBs4wFACjuTfCuDLJKeu93tThj889Dn1xAQyC",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/2ea5198b19f4bdf8c3b56d4e9d684fd8_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@exitliqexe",
    hue: 58,
  },
  {
    id: "DVFYHV",
    name: "Altcoinist",
    ticker: "ALTCOI",
    wallet: "DVFYHVKFYLxws4bV97va6EceVRrKjddHSWYq3is4ad49",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/f66e70231857aa5a2f7fe491be5a7b03_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Altcoinist",
    hue: 277,
  },
  {
    id: "EjhX8R",
    name: "Stańczyk",
    ticker: "STANCZ",
    wallet: "EjhX8RakDRQzxg8YHAPDvVNPp2eog8bWX26KDmhivBhf",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/bf970c63a7beb71eb847411dfd6d1a03_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xstanczyk",
    hue: 148,
  },
  {
    id: "7sQJtt",
    name: "eric.eth",
    ticker: "ERICET",
    wallet: "7sQJttJLutWjHkxbusTgE4GpSj5z4fegouv2USHDFN2H",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/582f58442baeed7b5a40bb90d7af6e0e_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@econoar",
    hue: 169,
  },
  {
    id: "HWYpE6",
    name: "B The Bezel",
    ticker: "BTHEBE",
    wallet: "HWYpE693cw8AWxHSynrHhUsKDbfzubAFYWpTcMZdNWKR",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/580a8fda17b5f7a819ae4fa658f39e6d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@BtheBezel",
    hue: 228,
  },
  {
    id: "5RZPhP",
    name: "333",
    ticker: "X333",
    wallet: "5RZPhPW9qGEd3hRGibgYaF5Yk2jBzXR1VZMKSP71C3Lb",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/bfb5551fae6c18782f500eab0813bfde_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@macdegods",
    hue: 75,
  },
  {
    id: "CGJfyg",
    name: "modeincognito",
    ticker: "MODEIN",
    wallet: "CGJfygZNh1jQqcrXJXRub1TNVt3FyMhG8n9y6v6fJ98d",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/4968b39f77b4a3093515de068eb768dd_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@modeincognito",
    hue: 185,
  },
  {
    id: "D9tPQe",
    name: "Him",
    ticker: "HIM",
    wallet: "D9tPQeij7vSTZwkxzxZibso4GFuRW8aBMpCg5QhCSfVL",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/570dabd7058fb70ad38ca95761b10696_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@himgajria",
    hue: 240,
  },
  {
    id: "5pHeNs",
    name: "‎ ‎ ‎",
    ticker: "NINETY",
    wallet: "5pHeNsWMVEi1cbMzLhgqABnhEUwRTSzy5vBfeGWyJfxS",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/747e61fb55945e52b644548c669f4431_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@ninety",
    hue: 104,
  },
  {
    id: "EU7FSV",
    name: "pricedin",
    ticker: "PRICED",
    wallet: "EU7FSVgkt8eZYV199enSCoQa3qoH6h6HP8v9BqpGDeG5",
    image: "",
    x: "",
    handle: "@pricedin",
    hue: 276,
  },
  {
    id: "DxM1hf",
    name: "RC",
    ticker: "RC",
    wallet: "DxM1hfY8FQ8dNGrucuJzhJcF8KRbjk8WBwrgKvQ9spPv",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/867ed6dec9d1ee779bf7d3438f7801ac_small?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@ResellCalendar",
    hue: 186,
  },
  {
    id: "Fwv2Sb",
    name: "OscarsProficy",
    ticker: "OSCARS",
    wallet: "Fwv2Sb8vUxbiYnJRF6Z92WdiTozCas1aXVPvCVNzAkCN",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/8359b5e9770a0861c19ff823e140e7c7_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@OscarsProficy",
    hue: 32,
  },
  {
    id: "498g1r",
    name: "frank 🎒",
    ticker: "FRANK",
    wallet: "498g1rVnFcnjBjpfw1xyqA1WvgQXUU8RWuELjxkjAayQ",
    image: "https://unavatar.io/x/frankdegods",
    x: "https://x.com/frankdegods",
    handle: "@frankdegods",
    hue: 281,
  },
  {
    id: "MTWazE",
    name: "zeus",
    ticker: "ZEUS",
    wallet: "MTWazEsbPPei3XPAcJzD1n3VpUeNinGYid4UVPx7FtY",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/072161c34cb264a8f30d0473d8a815da_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@zeustyy_",
    hue: 347,
  },
  {
    id: "DMTgKs",
    name: "acatwashere",
    ticker: "ACATWA",
    wallet: "DMTgKsvm44d76mrY7sWUEvr9Tx7fsVc3XiadiwZBUAig",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/ced7f6e6cd05092b38901e3190013642_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@catsuki",
    hue: 224,
  },
  {
    id: "Eq64d9",
    name: "I've 100 dreams",
    ticker: "IVE100",
    wallet: "Eq64d9oxaHD7SHrH78bk4ULbyFQ6LY2w5eznHKXFe7Tg",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/e5ceed219024d94a26b4efa6ce0b2dc8_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xconnery",
    hue: 300,
  },
  {
    id: "6My97B",
    name: "SmokΞy",
    ticker: "SMOKY",
    wallet: "6My97BBVoJz3j7mQWFVz5pykFxMsCs44gjhaqmczcAND",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/40d7da4855a955bc449b8723dadb630d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@smokey0x",
    hue: 190,
  },
  {
    id: "FoN8ti",
    name: "iamfake",
    ticker: "IAMFAK",
    wallet: "FoN8tiAEz5StunSznpMTUkNET7UT6Wjs2KJRdFmeuA7q",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/1ee517e39037c0c7cb4ff145c23ed84d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xiamfake",
    hue: 99,
  },
  {
    id: "6zMVSe",
    name: "Binkieee",
    ticker: "BINKIE",
    wallet: "6zMVSeukMUMKu5tDsECh4QMqrCRZqTbTvuawztFfwNti",
    image: "",
    x: "",
    handle: "@Binkieee",
    hue: 204,
  },
  {
    id: "HDPULy",
    name: "jakey",
    ticker: "JAKEY",
    wallet: "HDPULyHhMqwfWh45z2fQoGzmdp6dcRihy57dxucmrScg",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/916a82e4168d5d52532e9bfedc62aaee_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@jakeyPRMR",
    hue: 62,
  },
  {
    id: "8UPSoa",
    name: "DegenDan",
    ticker: "DEGEND",
    wallet: "8UPSoafmrq2h8GjFBKbsyHDZmcwRVM3ao9MdgJMEVJb6",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/e051db616e8c0ace0b4bb30015c8e3a4_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Degendan",
    hue: 122,
  },
  {
    id: "BUg6Pi",
    name: "Asado_Dreams",
    ticker: "ASADOD",
    wallet: "BUg6Pi7ba7TBM8zuVNffMF4V9GRaX56AF4BQbrzPr1Qg",
    image: "",
    x: "",
    handle: "@asado_dreams",
    hue: 120,
  },
  {
    id: "CH5wKB",
    name: "358",
    ticker: "X358",
    wallet: "CH5wKB99pfkQhf882XoakYCZ9NFgEgAuVr4s7opvwiYZ",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/67dcd7378b45bba1579459c3d3bc6f50_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@cosmic358",
    hue: 93,
  },
  {
    id: "67nTyh",
    name: "MIRRO🔶 BNB",
    ticker: "MIRROB",
    wallet: "67nTyhpE8wk4jfv6NduxS6S6kGjAEDnD62j64cqsqYvV",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/cb8a579e1b7bb900b114d79beebe0cba_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Mirro7777",
    hue: 135,
  },
  {
    id: "DeXdQ9",
    name: "brokeSzn",
    ticker: "BROKES",
    wallet: "DeXdQ9HhUyaVQ3UaYeHXTtmHCMbw5B6fhGLHXudRGwji",
    image: "",
    x: "",
    handle: "@brokeSzn",
    hue: 12,
  },
  {
    id: "83QpSe",
    name: "0xBEC001",
    ticker: "X0XBEC",
    wallet: "83QpSeVuT2T1YhyRZ8ce5joLe6TBF7PjvyCPWhdFvzYt",
    image: "",
    x: "",
    handle: "@0xBEC001",
    hue: 340,
  },
  {
    id: "C8MYME",
    name: "George Droid",
    ticker: "GEORGE",
    wallet: "C8MYMEppzQdvx7wQp4oeJHatYtSDPkibYyXPHUr4F9ke",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/c6b3de4f219aa59a24675d90a3d20dae_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@GeorgeDroid",
    hue: 42,
  },
  {
    id: "5e8R87",
    name: "NGOP",
    ticker: "NGOP",
    wallet: "5e8R87WwpvFj2VdbKvnGo48ZV8YPRhsgS5So4Ho6BcVw",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/114c3cf0e7d0bdcce8f6d65d41069d92_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@NoGiOlMoKiNi",
    hue: 286,
  },
  {
    id: "4GueRm",
    name: "blane",
    ticker: "BLANE",
    wallet: "4GueRmTvBQ3f2CFu5dnmEZ7aN5MkcBm32k6oNnGbeXs6",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/2b5fb78fe49822e4c537f2ed9042a31d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@blvnee",
    hue: 308,
  },
  {
    id: "8pPVis",
    name: "HUMANbeingET",
    ticker: "HUMANB",
    wallet: "8pPVisw9xJ6pKp3M7GdJg9nQ1fRZm1dmfVGu2tevzahe",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/6eeb3813f9317ac3a3cb2960c9aa8dc5_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@humanbeingET",
    hue: 31,
  },
  {
    id: "Gxir4q",
    name: "generational fumble",
    ticker: "GENERA",
    wallet: "Gxir4qAwqMh96gUskLkAct3fmWpdDDuwFHfwThPLofoV",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/84541ea795ea4cd71bb244f2cda6c5e6_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@GenerationalFumbler",
    hue: 37,
  },
  {
    id: "FKwZys",
    name: "malk",
    ticker: "MALK",
    wallet: "FKwZyspNpxecNLWwXACNcRT5VBHS5MrrWTx2RgfUEaQU",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/f3b0231a4fab1b7bb0d7ea3bebc685a2_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@malk",
    hue: 178,
  },
  {
    id: "9ab9J1",
    name: "币真的很好但是我需要生活",
    ticker: "NIYEDI",
    wallet: "9ab9J1hMmkgvNUpNHfNh85qrtYHAiEujyfYb2xSJhiFr",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/f8ebd97f904f212b1969ba4f177f5a8a_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@niyedie",
    hue: 154,
  },
  {
    id: "BgQPup",
    name: "JohnnyBones",
    ticker: "JOHNNY",
    wallet: "BgQPupJ8U7TnZtZTQ1FzAD7LqsJNjtZZXGPqfnrtZVQJ",
    image: "",
    x: "",
    handle: "@JohnnyBones",
    hue: 296,
  },
  {
    id: "8fR8rF",
    name: "neetguy",
    ticker: "NEETGU",
    wallet: "8fR8rFuNvKg9Y2B19nwei9W9xRY3ViD3bhyLytD1V8CM",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7ddef1f1c2249dd5d1670d3786a78b89_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@neetguy",
    hue: 216,
  },
  {
    id: "3ecWnX",
    name: "DeepThrobbingValue",
    ticker: "DEEPTH",
    wallet: "3ecWnXwqkTxUP9h9piLKLM9Cks939aoqi6RYEXbnnLon",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/b7b057b8abfaca1227b126153268d142_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@gweil0rd",
    hue: 137,
  },
  {
    id: "9PLvx6",
    name: "oznek",
    ticker: "OZNEK",
    wallet: "9PLvx6JvBmnNZHgsJBRGphgKJu8EJjviXuZdm4d1TcKd",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/94414e6e5499dd26f5ac6fa78827d02b_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@oznek",
    hue: 159,
  },
  {
    id: "2BjWby",
    name: "skylink",
    ticker: "SKYLIN",
    wallet: "2BjWbyCSd1hs4hycrP2DYfULQ4q4dDMVuKwW9ogSDHYv",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/31ad1d3dca0650271ce5e3561aed8674_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@sky_link",
    hue: 94,
  },
  {
    id: "CiFVDS",
    name: "brazen",
    ticker: "BRAZEN",
    wallet: "CiFVDSUpeZVSVQHgVVaa7bqoThUkwfRpYTronkaASWqY",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/537cd142d139d1e8efc72dfaea96c970_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@brazen",
    hue: 165,
  },
  {
    id: "NaCqF3",
    name: "byszzz",
    ticker: "BYSZZZ",
    wallet: "NaCqF3zmK3RLHmdX1AryM3iAFXtMzUapLGie7nHDen3",
    image: "",
    x: "",
    handle: "@byszzz",
    hue: 154,
  },
  {
    id: "GwXp9Z",
    name: "crypto1000x",
    ticker: "CRYPTO",
    wallet: "GwXp9ZsnxBZzSzTmwMQVxSn65ETyRnQHA36tWT6jSLey",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d9d89bef3e784c44a844b9011401d39e_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@crypto1000x",
    hue: 178,
  },
  {
    id: "BHKMWv",
    name: "that1618guy",
    ticker: "THAT16",
    wallet: "BHKMWvKsY3VXaVcibZP8wgMKQuerbpp5iofLgxrHXuTb",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/951f5406e961e8b6e59bdb1f780f5de0_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@that1618guy",
    hue: 222,
  },
  {
    id: "CPK7Jr",
    name: "dontsleeponme",
    ticker: "DONTSL",
    wallet: "CPK7JrooiYRyuDJdaipR9uBVt1zC9jLSfgkH1qJEmWRi",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/a8cf758c77ec02be85f1477c47fe45f6_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@dontsleeponme",
    hue: 43,
  },
  {
    id: "CDNBnR",
    name: "Goosemanjones",
    ticker: "GOOSEM",
    wallet: "CDNBnRyrXpBkh1R1iNpAHWn9BvCV4dHovMKBQsFusc8q",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/f17f1de9ad552c81c8e55d5a6cc12229_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@goosemanjones1",
    hue: 73,
  },
  {
    id: "J9k5KY",
    name: "jb (coinsexual, bull)",
    ticker: "JBCOIN",
    wallet: "J9k5KYANz5btiWVXWtjH28xvUTxfgo7ZbybcEUWLNsbd",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/900f8e31fbbee106e859892db8e4f106_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@montyMole44",
    hue: 172,
  },
  {
    id: "AXN4A7",
    name: "RareDualJay",
    ticker: "RAREDU",
    wallet: "AXN4A7HNzncqzD9KGSbiSzE58vqvQmQxn8jhfYCKx9ai",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/5aa7659cb7ad6499e8a54329c22c2b61_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@RareDualJay",
    hue: 227,
  },
  {
    id: "D5Z8GX",
    name: "Zach",
    ticker: "ZACH",
    wallet: "D5Z8GXQxTQ2vUdEYdaqLRbPZKGr1WMhdvQRSWna6EhJm",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d8f46ba808f99444a020193a5a8d11e7_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@CryptoZachLA",
    hue: 304,
  },
  {
    id: "9fnyoj",
    name: "tjrtradez",
    ticker: "TJRTRA",
    wallet: "9fnyojTv8GYHWr4Vaj4tvVL82scPPYYkW1CAXAbfUsdj",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/479d82dd555343b24751b77df8cc219d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@tjr",
    hue: 279,
  },
  {
    id: "9qgh1e",
    name: "0xSawce",
    ticker: "X0XSAW",
    wallet: "9qgh1edYnZwGotFHzF2RPhPwKPTWTL9oB793NuFjzMcX",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/4076e52787b3fc0a82f416165387d20f_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xSawce",
    hue: 72,
  },
  {
    id: "EmZjHy",
    name: "workethic",
    ticker: "WORKET",
    wallet: "EmZjHyv5twFhFRnh8KQ6vnr3sY5mDiDDK19z776kNdHg",
    image: "",
    x: "",
    handle: "@workethic",
    hue: 24,
  },
  {
    id: "JAJBDT",
    name: "Don Coinleone",
    ticker: "DONCOI",
    wallet: "JAJBDTMVYEWUScmUiqwbqUFMwQytSKYo97Sv6qTUChso",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7a81789573742cb771ffaaff4a14cb61_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@maxbax88",
    hue: 321,
  },
  {
    id: "8i3j6R",
    name: "blur",
    ticker: "BLUR",
    wallet: "8i3j6R4A4d7aNep9q6ZWsLhyNGU2YzU9GqgjrASxeLw9",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/65cd3b2080e618d0d8910681026f05cb_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@almonte",
    hue: 268,
  },
  {
    id: "7Y72Tm",
    name: "Coached",
    ticker: "COACHE",
    wallet: "7Y72TmQLF2sDcJTL84o4Nimtvtb7xLf22CVBkuxxdcws",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/772ac5d488ea79e5a05064d7900ca471_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@coached",
    hue: 125,
  },
  {
    id: "9EhcDG",
    name: "lordarbiter",
    ticker: "LORDAR",
    wallet: "9EhcDGGJ6NpetxNumZKwD1o1kuHBwvfNGKrmS6zekP7C",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/b26ea85a7dae8eabec39deb8e91c5613_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@lordarbiter",
    hue: 126,
  },
  {
    id: "GvhzWw",
    name: "rangevertical",
    ticker: "RANGEV",
    wallet: "GvhzWwCWVouppmiUrivUdyisR1mmwsNXAT6z626bkSsG",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/bc85ac3b00ed1c623be1140dee08ec17_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@CeruleanRange",
    hue: 311,
  },
  {
    id: "H8uUf8",
    name: "0xLeaf🍃",
    ticker: "X0XLEA",
    wallet: "H8uUf8eTNshEy4bS7AKi7Wn2LikgkwQaSEn6ypdweFxm",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/5f129a27fadb3e97ab4873e248de80f4_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@3ethtomoon",
    hue: 298,
  },
  {
    id: "DRJwmN",
    name: "BigPoppa",
    ticker: "BIGPOP",
    wallet: "DRJwmNnhDZdRuNJzxrKZrp2E8RqjvsNRZQRZy8YWPviy",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/e3cd43e0ffcc60beec4fc74b5e0c1307_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@BeggeSol",
    hue: 219,
  },
  {
    id: "6MsBTR",
    name: "escobarpablo",
    ticker: "ESCOBA",
    wallet: "6MsBTRvTtmXyHSQNSr7poB6ChhMKtS3AuG98Wg5fEh4o",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/13f55e5469290581b59b86a6f11d86dc_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@escobarpablo",
    hue: 87,
  },
  {
    id: "BHNR9D",
    name: "dye",
    ticker: "DYE",
    wallet: "BHNR9DvAe699r1nywZmRZGMb7T6tx8r22iP8EsiHJ9fx",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/bd182857bc5f80eed5d8f4d146f33f98_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@dyex0",
    hue: 269,
  },
  {
    id: "ByQwyb",
    name: "scripting",
    ticker: "SCRIPT",
    wallet: "ByQwybKUzjfVueDP5viPwnbE1dbQJrxUVzsy6VZQMWTB",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/36f3231fcd7e1eb9858a4bc12e39a973_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xscripting",
    hue: 310,
  },
  {
    id: "9n4YTp",
    name: "sir chaz p.",
    ticker: "SIRCHA",
    wallet: "9n4YTpjrfo4QcaPECng374QZjZpbvpeSvosBF9ZjZUkP",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/a4b62a712fdf562d33f65118dd4cd84f_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@attnmarkets",
    hue: 249,
  },
  {
    id: "3xEgQC",
    name: "iykyk𐙚",
    ticker: "IYKYK",
    wallet: "3xEgQCqNhJGHqavQzEFpmet8Vtc6o1L43snhRFeVLE1w",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/1863450b427ccc1111100971ced0ad13_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@onchaincutie",
    hue: 62,
  },
  {
    id: "CZPVN8",
    name: "kb (achilles bull)",
    ticker: "KBACHI",
    wallet: "CZPVN8ucAkFfWUuKzGzL21Y6k1RvBo8bQLFHCcvi75z4",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/602a6eb292adf12717f39f5c783429c5_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@achilles_bull",
    hue: 71,
  },
  {
    id: "2GHFFN",
    name: "FancyGrandSkink",
    ticker: "FANCYG",
    wallet: "2GHFFN5dNa7fApfqxNW5MFq4diC4DZHHgkdwP46LfmDg",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d312d5ec3d471db7f2d7e9e2740ffe0a_small.jpg?k=2610PBUCH3e-3sLef6I8vaZRA",
    x: "",
    handle: "@FancyGrandSkink",
    hue: 37,
  },
  {
    id: "8QcfLo",
    name: "teep",
    ticker: "TEEP",
    wallet: "8QcfLoVEgrjGA7iHAKxRbryoRRCQwDaUyZDjVwW2UkXz",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/40e5b9a36dde7057cb6f90670b1f6728_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@teepanddestroy",
    hue: 127,
  },
  {
    id: "JDFDma",
    name: "Logan Lim",
    ticker: "LOGANL",
    wallet: "JDFDma1TMb1tWNFY1pruwCsHBybMdzwxveythZB2dcaG",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/e07cf12864bc315490934513347ff8f6_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@loganlim_x",
    hue: 254,
  },
  {
    id: "3MaAte",
    name: "juicy",
    ticker: "JUICY",
    wallet: "3MaAteeSjeovHX1HA3d54UZh2GAJAo5jH7BCSuaz9LSd",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7129bafa2534e503ec9356b11814479a_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Juicycooks",
    hue: 28,
  },
  {
    id: "XB7y64",
    name: "trigger",
    ticker: "TRIGGE",
    wallet: "XB7y64PqS26sKp5ry3m62m8AJ9egBh676PruSzYGY4H",
    image: "",
    x: "",
    handle: "@triggerwarning",
    hue: 67,
  },
  {
    id: "FgCteM",
    name: "Tendychallenge",
    ticker: "TENDYC",
    wallet: "FgCteMk5NCERqR4u2RWjfZ9SPA5kpw2yGnsPYMUQ8zyA",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/1f8920ba428c092c782ec4f6f2d04267_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@TendersAlt",
    hue: 100,
  },
  {
    id: "Dp7RHV",
    name: "squid27",
    ticker: "SQUID2",
    wallet: "Dp7RHVhqYpDm5j5AjW55T2YfnHGfNee1LAQXyEihUMLj",
    image: "",
    x: "",
    handle: "@squid27",
    hue: 168,
  },
  {
    id: "95retN",
    name: "finne",
    ticker: "FINNE",
    wallet: "95retNLGNuJzrUFMYjHhBSRB3T7PaGyPn4FpuoGLhWaF",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/3aa21f80cae3d45f3f43d46ed05e175c_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xfinne",
    hue: 217,
  },
  {
    id: "2Po4gN",
    name: "boston",
    ticker: "BOSTON",
    wallet: "2Po4gNFPYksMtymxg9H1Mz5RpxYUipKMjoRG513E2dfy",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/ee649a0c9cd0da3ee2bff30b1d103cda_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@bostoncapital",
    hue: 23,
  },
  {
    id: "GNiidb",
    name: "Unipcs_Intern",
    ticker: "UNIPCS",
    wallet: "GNiidb7bDxgw9ucaueiwdnGNzivQXSqeHd8DNoQojJuQ",
    image: "",
    x: "",
    handle: "@UnipcsIntern",
    hue: 137,
  },
  {
    id: "3Wxibu",
    name: "MXD",
    ticker: "MXD",
    wallet: "3WxibuvNHxSfMY5mBXfzqmbA3svtKpWBUtCqan33PxJS",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/0f106d694d372d01de6ce049542f7586_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@MINHxDYNASTY",
    hue: 69,
  },
  {
    id: "8m33WQ",
    name: "foreveryoung",
    ticker: "FOREVE",
    wallet: "8m33WQXiz5p4UpwotJTbSha5yczmfx5WgeuMdX9UWxbQ",
    image: "",
    x: "",
    handle: "@foreveryoung",
    hue: 310,
  },
  {
    id: "6tsZ4J",
    name: "BLSZY",
    ticker: "BLSZY",
    wallet: "6tsZ4JeaNNvD8TTTbxccL1LmpnF6tT4hDpd2cXbm8Toh",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/cc5714d5fd79cbe4808686aab7637a01_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@BLSZY",
    hue: 286,
  },
  {
    id: "78awt2",
    name: "Slime.",
    ticker: "SLIME",
    wallet: "78awt213YXv8mRvDpaGPP4AGJCKH6C3x12cTkwmFXfgc",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/455a932bc7219185b0b78c4276595c3a_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@holehighGC",
    hue: 8,
  },
  {
    id: "Gsr45R",
    name: "Fiskanto",
    ticker: "FISKAN",
    wallet: "Gsr45RRFCYpCXqHD9c8Ykip8SB7EuZ6yD5wVCbsgtfy4",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/a6ec13f9f768f86e371a4c174ea3b1f9_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Fiskanto",
    hue: 211,
  },
  {
    id: "GpHkiR",
    name: "Dxrant",
    ticker: "DXRANT",
    wallet: "GpHkiRzoJDNPpDVgMx2E3xamrxogHKGaZg4HahQxhRVB",
    image: "https://unavatar.io/x/Dxranteth",
    x: "https://x.com/Dxranteth",
    handle: "@Dxranteth",
    hue: 34,
  },
  {
    id: "8P6if1",
    name: "Thesis",
    ticker: "THESIS",
    wallet: "8P6if1gvtR1ZVNGN6gyLCkxQ6sDEn4JDiHEh3H7534hu",
    image: "",
    x: "",
    handle: "@Thesis_",
    hue: 81,
  },
  {
    id: "DcbxVE",
    name: "Clewguo",
    ticker: "CLEWGU",
    wallet: "DcbxVEezcXbCPiZKhCU3ZHeYXBfKeQxnDfCMPJ6vhUoo",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d62b341d1cc2b04c0fbb28f89e04f92d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@clewguo",
    hue: 168,
  },
  {
    id: "BPotSw",
    name: "FreeAliveMole",
    ticker: "FREEAL",
    wallet: "BPotSw6qBfV2HY5PUoK9CjUu5zXdWoxdj4jveohH7Wfe",
    image: "",
    x: "",
    handle: "@FreeAliveMole",
    hue: 129,
  },
  {
    id: "J2TNcj",
    name: "Camikaze Capital",
    ticker: "CAMIKA",
    wallet: "J2TNcjujEEnE1RBmWrBTxPZvj98dvAHb37BRdRw7VNe9",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/9ea64066e1f84cbef2ffbb9dfbd1b1da_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@CamikazeCapital",
    hue: 40,
  },
  {
    id: "5hvWbB",
    name: "pain",
    ticker: "PAIN",
    wallet: "5hvWbBdyAwiuNUy7Ts6huS1KW2ijiHMZqku2LBM4ncTZ",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/44bf41e7c10bc321d6778bdd8ae94b45_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@pain",
    hue: 336,
  },
  {
    id: "HcSVPf",
    name: "Grovyle",
    ticker: "GROVYL",
    wallet: "HcSVPfDiM532GZFs3pnrAKVqrriqJBMH8Y5DirxhLDrS",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7a8fcd0c3409e9281abcd6d4d6b7ee75_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Grovyle",
    hue: 123,
  },
  {
    id: "AFmiex",
    name: "Badabeep",
    ticker: "BADABE",
    wallet: "AFmiexHwMBFjKY7N9spbYjeKCr2nmj6k7zmAaamcjkVy",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/b65182697d752771570d23fceda639ad_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@badabeepp",
    hue: 90,
  },
  {
    id: "DAejzM",
    name: "fomopumpguy",
    ticker: "FOMOPU",
    wallet: "DAejzMs5cUeCCENNvapy9KWFwzwegh7LvcgNkZ6hnf1y",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/31ba281e31529e45542a2857a39ad9eb_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@fmpumpguy",
    hue: 122,
  },
  {
    id: "B8vkaU",
    name: "Narrow Chances",
    ticker: "NARROW",
    wallet: "B8vkaU8x1hp66efVXgwsdgMXyrLayhgyL2mTK1KsihRi",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/3a101526eba4a90f8b2d25ac80f69e6d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@narrowww",
    hue: 356,
  },
  {
    id: "DeFdPb",
    name: "chrollo🕷",
    ticker: "CHROLL",
    wallet: "DeFdPbeBvJRyhpRQTgsPq63mHCWNkWBj1zjCZ28o2qMc",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/9577f53359edca513f02d80532af8db5_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@chrollo0o0",
    hue: 347,
  },
  {
    id: "BnUC52",
    name: "Crispy Biscuit",
    ticker: "CRISPY",
    wallet: "BnUC52kCpjwFSnB97BJrbhH8ByHM15NoUjgrVBPR8DHT",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/78856a6c8bd0d25bf11d601982cb1321_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@SneakyNinjaPantalones",
    hue: 266,
  },
  {
    id: "GEWNoA",
    name: "RudeOuterStork",
    ticker: "RUDEOU",
    wallet: "GEWNoAdwVxymFrDMdA7Mj157ZFiSWoJKF3xytppV49Qu",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/16a9c2655ee494f2a3a86c4df55bbef4_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@RudeOuterStork",
    hue: 185,
  },
  {
    id: "FgJXjn",
    name: "Mochicapital08",
    ticker: "MOCHIC",
    wallet: "FgJXjntZVVc78KdHkrsFFYZvXj7PhrHZrH9pqjQT92ix",
    image: "",
    x: "",
    handle: "@Mochicapital08",
    hue: 309,
  },
  {
    id: "59Q3zu",
    name: "0x_Cinema",
    ticker: "X0XCIN",
    wallet: "59Q3zuUHcwpg6YSkbJ2h8oE11vZhFcJdoSn8LhNC992H",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/83900969ddd9b3bdfac921495aacfa29_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0x_Cinema",
    hue: 250,
  },
  {
    id: "7Dycvf",
    name: "Avon",
    ticker: "AVON",
    wallet: "7DycvfJbmapgPoGPKPU6SLrfFEkgD43xRpc2FSsWHAn4",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/f347483c35f2bd1a52a597c4ce0d898f_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Barksdale",
    hue: 234,
  },
  {
    id: "CzU8Ma",
    name: "Rowdy",
    ticker: "ROWDY",
    wallet: "CzU8MaRcwvwUoNkwJFLbvtFWJugcEXAhDDQqNFE4ybb7",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/14c9474182c1f53368459b183dbd8ecc_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@Rowdy",
    hue: 310,
  },
  {
    id: "D7RsPj",
    name: "K A L E O",
    ticker: "KALEO",
    wallet: "D7RsPj1Hq8Xp619ZqCFQTCxNhQXas5N3KJSoEPkgUo3x",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d258e4fd4b0a42d2ac5c2b9df72d55db_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@CryptoKaleo",
    hue: 332,
  },
  {
    id: "EDaeKc",
    name: "mdpl",
    ticker: "MDPL",
    wallet: "EDaeKceLxTqTFFsSURLyKia2EWWLHzpZNg92nbGRK9Dh",
    image: "",
    x: "",
    handle: "@mdpl",
    hue: 64,
  },
  {
    id: "Hkk4yo",
    name: "devv",
    ticker: "DEVV",
    wallet: "Hkk4yo6LTfRB1B97jr7qx7rbqsaio5MGCKzseCqFjgcJ",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/47c5f69d68a4b649d8cdf1eb398b7bfb_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@devwyd",
    hue: 20,
  },
  {
    id: "8ABgLu",
    name: "wawawewe",
    ticker: "WAWAWE",
    wallet: "8ABgLuU3gxcCjrDVunPowXwDw9TLkxrNbAUXk3Epi1Gq",
    image: "",
    x: "",
    handle: "@wawawewe",
    hue: 272,
  },
  {
    id: "4Bc4Ue",
    name: "vvvvvvvvvv",
    ticker: "VVVVVV",
    wallet: "4Bc4Ue2G37zoQCiksAvwMgXQQJFKcYQThnoHPKizAmWB",
    image: "",
    x: "",
    handle: "@vvvvvvvvvv",
    hue: 20,
  },
  {
    id: "n6Lc9F",
    name: "JT",
    ticker: "JT",
    wallet: "n6Lc9Fh5Jfk5q7KPy1cdbW2ZxJERFicYJTXqQZJN7FU",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/6f9e57ac14d76ee6f1f5267595cd38be_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@thejefeee",
    hue: 246,
  },
  {
    id: "HHbnJK",
    name: "lordskies",
    ticker: "LORDSK",
    wallet: "HHbnJK8xshr57qz21foyyQLMvX61RPQs1vtdDmjaPdvW",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/b6ab392dceba70d9824801f0fe365d44_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@lordskies",
    hue: 86,
  },
  {
    id: "9MDujU",
    name: "Ozi 🐦‍⬛",
    ticker: "OZI",
    wallet: "9MDujULGXoY4gux9dqRDy5wi7pn6ekuunsq97VFqXMuR",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/c2e0cf78d6f635f067c0c2cdfbdbae63_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@ozi_chain",
    hue: 201,
  },
  {
    id: "DrxBsU",
    name: "X Ventures",
    ticker: "XVENTU",
    wallet: "DrxBsUd3ufx9Q8kc8Zts1SAavMccrAJcwrFzLf77d9o1",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7b17996fe0e093971f2fcf6c11e4d1e9_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@XVentures",
    hue: 124,
  },
  {
    id: "GbHcGc",
    name: "Prometheus",
    ticker: "PROMET",
    wallet: "GbHcGc9mjCRH7jiPJhPG7VeQbRC5LsarEeSCrJ7DbjNh",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/2d8fb7d2edf4f1eb515ccf7a111184b0_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@prometheusx91",
    hue: 240,
  },
  {
    id: "3YonHL",
    name: "maxx",
    ticker: "MAXX",
    wallet: "3YonHL3UNTv53MYFxyYAuaUwFjERNTJ8sUrgQS7BHuYq",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/f6995b572186476bce9a9a91aa4298ac_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@wealthmaxxer",
    hue: 340,
  },
  {
    id: "4Zk1e5",
    name: "mcmoohyun",
    ticker: "MCMOOH",
    wallet: "4Zk1e5GMx6a4srxrZUgZVVYjDeP2VHDVWLY6E9ZAZCV2",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/4392b6e53a9fc7a5ba5b7da78d85e640_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@mcmoohyun",
    hue: 132,
  },
  {
    id: "5vh3TZ",
    name: "excesscapital",
    ticker: "EXCESS",
    wallet: "5vh3TZMDWhP2WNJNtUjYYps21JPnY3HYpR13c22LBwAT",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/d7dc0511088a6b9e7069b91276b7db9d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@excesscapital",
    hue: 52,
  },
  {
    id: "FRT8Yu",
    name: "BIGWARZ",
    ticker: "BIGWAR",
    wallet: "FRT8YuLJ9q8PPX2o4RUiJ9hWL427hNmMJ2M6JdgGgzwK",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/3158e615bf2eaa60b349533b8eea2dcf_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@bigwarzeth",
    hue: 132,
  },
  {
    id: "2TyGCF",
    name: "CrudeStillGuan",
    ticker: "CRUDES",
    wallet: "2TyGCFChYFqaXjniSbpn9ggvLhKZ2LfGwY5TwLzwx9mb",
    image: "",
    x: "",
    handle: "@CrudeStillGuan",
    hue: 195,
  },
  {
    id: "Dg6Mai",
    name: "AnabolicMoney",
    ticker: "ANABOL",
    wallet: "Dg6MaiSjEwDS4Ph1Bm6bhXn8Nq56XbWNuJiA82hana2Q",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7c4e21311a91bdbce1327e2cbeb56498_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@bryyceb",
    hue: 327,
  },
  {
    id: "Fhg4k5",
    name: "Milst",
    ticker: "MILST",
    wallet: "Fhg4k5sNcMS4YTsu1gqdd3GWmG1dTT1pyQeaTbfye2Gf",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/577aed7aad9c665185401012feb20d15_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@MilstG",
    hue: 169,
  },
  {
    id: "HcyGXA",
    name: "industry plant",
    ticker: "INDUST",
    wallet: "HcyGXAxqS27PTpv4nGYZYR6u8NHWE3CeUArwnh8gfcRH",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/831853655210592d07f36bfbdb8d594b_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@industryplant777",
    hue: 177,
  },
  {
    id: "BeCm9g",
    name: "justswap",
    ticker: "JUSTSW",
    wallet: "BeCm9gD8f2DnLiv91Y6xDtLuSR9seFVsSakP3aBbchLr",
    image: "",
    x: "",
    handle: "@justcook",
    hue: 123,
  },
  {
    id: "ELx62u",
    name: "Coringtons",
    ticker: "CORING",
    wallet: "ELx62umUSwoVy713Mn9z2RsYsN3un7kdrtYi6zVFt11J",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/6766ff841614b4f2608c8f564a515237_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@coringtonite",
    hue: 54,
  },
  {
    id: "6zgP1L",
    name: "retardedPeecan",
    ticker: "RETARD",
    wallet: "6zgP1LDYiD7gE2nkFBcsgFTdW4wQedALcWaKkRsGic67",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/4fa6caa8e3a8f8b4afb693753749da89_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@retardedpeecan",
    hue: 82,
  },
  {
    id: "24JAhZ",
    name: "Xelas",
    ticker: "XELAS",
    wallet: "24JAhZew6zAXW47hHJTFmMZP7BgVefZ5Nyg4wz4S8Qcb",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/c798b64f0c9051ef5ffbd6d40ae7358e_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@xelasfi",
    hue: 208,
  },
  {
    id: "FbTvJL",
    name: "npckez",
    ticker: "NPCKEZ",
    wallet: "FbTvJLHooSfpAp4sb4PQCGFRd2VWzHjeApMUzit8vzKx",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/15ca66c808da6073b4441eacc73251aa_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@npckez",
    hue: 353,
  },
  {
    id: "EzKDs3",
    name: "prevaile",
    ticker: "PREVAI",
    wallet: "EzKDs32Qd396gg48HZKGibvfAdS27KTmcCfdEp6euSLt",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/c8f702587bde354117c93654597e3f81_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@prevaile",
    hue: 265,
  },
  {
    id: "45HGm4",
    name: "The Wheeler Dealer 🌍",
    ticker: "THEWHE",
    wallet: "45HGm4EMV8SeaPwCc4E6PvZVHZsxcT7dsSKHiBaRUp4E",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/25d29e8bb219f4d3b68b800d0a46b91d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@WheelerrDealerr",
    hue: 130,
  },
  {
    id: "AfYkux",
    name: "Vanta",
    ticker: "VANTA",
    wallet: "AfYkuxAGgFV7k6XV8uB733spZZSdBJzuuTKwiuHxb42b",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/7d253d9ec288e64d9a06d16bcaf1673d_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xVantaa",
    hue: 77,
  },
  {
    id: "H9TtRQ",
    name: "0xyyy1618",
    ticker: "X0XYYY",
    wallet: "H9TtRQTMzgwDarXCPgkT8yw7MotjGvJWZ854Z8Yn5CQE",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/781dfff54c9c0f2cc5f509476bdbebfa_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@0xnneged",
    hue: 302,
  },
  {
    id: "navoLm",
    name: "Unc Sniper",
    ticker: "UNCSNI",
    wallet: "navoLmYzqYeawqsHedm5CZLAP5YXhwGW3xDchYsWqBT",
    image:
      "https://prod-fomo-profile-pics.s3.amazonaws.com/463838eefb26a4a3c021d8f70ef10d12_small.jpg?k=272B3mL_Jk2GW2Kjyo6JUNihg",
    x: "",
    handle: "@uncsnipes",
    hue: 339,
  },
  {
    id: "BvApEL",
    name: "midtermdevv",
    ticker: "MIDTER",
    wallet: "BvApEL9H3nnn2mezyUQQsSxvnwwBpkVFF3Yh61MZSruZ",
    image: "https://unavatar.io/x/MidTermDev",
    x: "https://x.com/MidTermDev",
    handle: "@MidTermDev",
    hue: 109,
  },
  {
    id: "8k1BPp",
    name: "panic",
    ticker: "PANIC",
    wallet: "8k1BPp8pCxq7RJxxBz3BUxvBjsfjhkHKnhr2WSQABGM9",
    image: "https://unavatar.io/x/panicselling",
    x: "https://x.com/panicselling",
    handle: "@panicselling",
    hue: 175,
  },
  {
    id: "3bzaJd",
    name: "MattFws",
    ticker: "MATTFW",
    wallet: "3bzaJd5yZG73EVDz8xosQb7gfZm2LN5auFGh6wnP1n1f",
    image: "https://unavatar.io/x/MattFws",
    x: "https://x.com/MattFws",
    handle: "@MattFws",
    hue: 7,
  },
  {
    id: "GijFWw",
    name: "lunarfang",
    ticker: "LUNARF",
    wallet: "GijFWw4oNyh9ko3FaZforNsi3jk6wDovARpkKahPD4o5",
    image: "https://unavatar.io/x/lunarfang_416",
    x: "https://x.com/lunarfang_416",
    handle: "@lunarfang_416",
    hue: 102,
  },
  {
    id: "6Cpipy",
    name: "ronaldcarter",
    ticker: "RONALD",
    wallet: "6CpipySaXTAiUKDyyhWeCfYSMQLCiHrbCN1WvRv5s8kF",
    image: "https://unavatar.io/x/USronaldcarter",
    x: "https://x.com/USronaldcarter",
    handle: "@USronaldcarter",
    hue: 196,
  },
  {
    id: "EnPjBj",
    name: "collectible",
    ticker: "COLLEC",
    wallet: "EnPjBjzy6zaufzpZ2m3Q8nPS3KpyiRxNLKtcSiMYwWCa",
    image: "https://unavatar.io/x/collectible",
    x: "https://x.com/collectible",
    handle: "@collectible",
    hue: 240,
  },
  {
    id: "68XiYb",
    name: "fakejoji",
    ticker: "FAKEJO",
    wallet: "68XiYbqQedUbV1EboBhtZDtTTzX4vwUBzKB6rbUGPvHj",
    image:
      "https://pump.mypinata.cloud/ipfs/bafkreigvtyu2xnexnf3ee36avdarlzgmvigd5pnhnrs3lszzgcidci22om",
    x: "",
    handle: "@fakejoji",
    hue: 80,
  },
  {
    id: "8AtQ4k",
    name: "peacefuldestroy",
    ticker: "PEACEF",
    wallet: "8AtQ4ka3dgtrH1z4Uq3Tm4YdMN3cK5RRj1eKuGNnvenm",
    image: "https://unavatar.io/x/peacefuldestroy",
    x: "https://x.com/peacefuldestroy",
    handle: "@peacefuldestroy",
    hue: 298,
  },
  {
    id: "B5TrL7",
    name: "sapphy",
    ticker: "SAPPHY",
    wallet: "B5TrL7PsRUwCTL5bVcueieht5QchTw4TWLQDKqEaxEzi",
    image:
      "https://pump.mypinata.cloud/ipfs/bafkreiexwvpqvkuqvke7dtvbzmpnta4duodgtl33z5jo5gakydgxf2ha2y",
    x: "",
    handle: "@sapphy",
    hue: 354,
  },
  {
    id: "29yFze",
    name: "throatycrab1008",
    ticker: "THROAT",
    wallet: "29yFzeBZgxf5zqrAkKXwgZtQehRf4pL8WbV2nRJikbw8",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Amber~Body-Green~Face-5~Glasses-black~Hairstyle-4---Red~Watch~Bowtie-Green.webp",
    x: "",
    handle: "@throatycrab1008",
    hue: 285,
  },
  {
    id: "6i2aHt",
    name: "sapijiju",
    ticker: "SAPIJI",
    wallet: "6i2aHtxfqkC2biTo98FSkP59FVHPKFRLZWDbdghN6WKK",
    image: "https://unavatar.io/x/sapijiju",
    x: "https://x.com/sapijiju",
    handle: "@sapijiju",
    hue: 14,
  },
  {
    id: "f4CMmX",
    name: "Cirrus",
    ticker: "CIRRUS",
    wallet: "f4CMmXJCRu4fzyqZPkDiFhGKAeCo1s7sxUtPKQp9SDy",
    image: "https://unavatar.io/x/CirrusNFT",
    x: "https://x.com/CirrusNFT",
    handle: "@CirrusNFT",
    hue: 131,
  },
  {
    id: "4vw54B",
    name: "notdecu",
    ticker: "NOTDEC",
    wallet: "4vw54BmAogeRV3vPKWyFet5yf8DTLcREzdSzx4rw9Ud9",
    image: "https://unavatar.io/x/notdecu",
    x: "https://x.com/notdecu",
    handle: "@notdecu",
    hue: 97,
  },
  {
    id: "4Be9Cv",
    name: "mitch",
    ticker: "MITCH",
    wallet: "4Be9CvxqHW6BYiRAxW9Q3xu1ycTMWaL5z8NX4HR3ha7t",
    image: "https://pump.mypinata.cloud/ipfs/Qmf34MNCGCn5hS97s7gLwzqQMKfR7pSLADJRB4VwPrhTvQ",
    x: "",
    handle: "@mitch",
    hue: 33,
  },
  {
    id: "5hAgYC",
    name: "schoen",
    ticker: "SCHOEN",
    wallet: "5hAgYC8TJCcEZV7LTXAzkTrm7YL29YXyQQJPCNrG84zM",
    image: "https://unavatar.io/x/Schoen_xyz",
    x: "https://x.com/Schoen_xyz",
    handle: "@Schoen_xyz",
    hue: 138,
  },
  {
    id: "3VUNtV",
    name: "buddhaaaaa",
    ticker: "BUDDHA",
    wallet: "3VUNtVtjjx5ckUojT7UocJ5fbuAJRsNUXNfTBnPte9vC",
    image: "https://unavatar.io/x/mofo_chad",
    x: "https://x.com/mofo_chad",
    handle: "@mofo_chad",
    hue: 115,
  },
  {
    id: "ardinR",
    name: "trunoest",
    ticker: "TRUNOE",
    wallet: "ardinRsN1mNYVeoJWTBsWeYeXvuR9UUDGMsCDKpb6AT",
    image: "https://unavatar.io/x/trunoest",
    x: "https://x.com/trunoest",
    handle: "@trunoest",
    hue: 214,
  },
  {
    id: "2KQKDA",
    name: "abil",
    ticker: "ABIL",
    wallet: "2KQKDA9RtgB8wfGMcnGsKMfFY2BkktG2ETMtRPSAzB8C",
    image: "https://unavatar.io/x/Abilahbr",
    x: "https://x.com/Abilahbr",
    handle: "@Abilahbr",
    hue: 155,
  },
  {
    id: "BqhAPg",
    name: "NRv_",
    ticker: "NRV",
    wallet: "BqhAPgnScqDUP9f7fFuqrZn8WRznduGT7VvPzbUjHnT7",
    image: "https://unavatar.io/x/NRv_gg",
    x: "https://x.com/NRv_gg",
    handle: "@NRv_gg",
    hue: 39,
  },
  {
    id: "HTcPDp",
    name: "workerzzz",
    ticker: "WORKER",
    wallet: "HTcPDpzxMuMZF9Xbb7iTHGsZ77BFUGqJPqDp2GefnuWQ",
    image:
      "https://socialimages.pump.fun/profile-images/5451f43f-cea4-4863-9187-2450f7fdcbf5/74e73080-d51b-4341-9535-f622ca5bdf04",
    x: "",
    handle: "@workerzzz",
    hue: 262,
  },
  {
    id: "7CscJr",
    name: "Pumpguy0x",
    ticker: "PUMPGU",
    wallet: "7CscJrKVE64TvXXNS3uRQ3aQXmdSfWcrBYBSRcxwCUtw",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Pink~Body-3-Emerald-wand~Face-7~Glasses-brown~Cap-Green~Bracelet-orange~Empty+2.webp",
    x: "",
    handle: "@Pumpguy0x",
    hue: 72,
  },
  {
    id: "9LXWa7",
    name: "rikz_",
    ticker: "RIKZ",
    wallet: "9LXWa7V3AE15VfBupcx5gDts2ix3Y9NzbcKZKjkkq6hV",
    image: "https://unavatar.io/x/kenAbz",
    x: "https://x.com/kenAbz",
    handle: "@kenAbz",
    hue: 356,
  },
  {
    id: "GeUnv1",
    name: "Gladey",
    ticker: "GLADEY",
    wallet: "GeUnv1jmtviRbR7Gu1JnXSGkUMUgFVBHuEVQVpTaUX1W",
    image: "https://unavatar.io/x/Gladey777",
    x: "https://x.com/Gladey777",
    handle: "@Gladey777",
    hue: 170,
  },
  {
    id: "AusMtC",
    name: "Uniswapvillain",
    ticker: "UNISWA",
    wallet: "AusMtCwzrPnPoJUSHYUH9iogVwpWh2ESHC6xWU75tBDo",
    image: "https://unavatar.io/x/UniswapVillain",
    x: "https://x.com/UniswapVillain",
    handle: "@UniswapVillain",
    hue: 23,
  },
  {
    id: "2MRDbE",
    name: "asta",
    ticker: "ASTA",
    wallet: "2MRDbEMVJgmV6fnkQDaeFicEMtw6BqV81284goJ6dKtc",
    image: "https://unavatar.io/x/astaso1",
    x: "https://x.com/astaso1",
    handle: "@astaso1",
    hue: 278,
  },
  {
    id: "2Nsevs",
    name: "y22",
    ticker: "Y22",
    wallet: "2NsevsKWiaDtEiYF5gGLCVGNBwsLNibgppoiVPHHYrqq",
    image: "https://unavatar.io/x/real_y22",
    x: "https://x.com/real_y22",
    handle: "@real_y22",
    hue: 12,
  },
  {
    id: "EeXvxk",
    name: "allglorybetogod",
    ticker: "ALLGLO",
    wallet: "EeXvxkcGqMDZeTaVeawzxm9mbzZwqDUMmfG3bF7uzumH",
    image: "https://unavatar.io/x/fnmilito",
    x: "https://x.com/fnmilito",
    handle: "@fnmilito",
    hue: 48,
  },
  {
    id: "HVaeUP",
    name: "RoaringKitty",
    ticker: "ROARIN",
    wallet: "HVaeUPbAwFhZnY8T3MrUzTWqpHiAbTU1NACmCQdJrqZp",
    image: "https://unavatar.io/x/RoaringKitty",
    x: "https://x.com/RoaringKitty",
    handle: "@RoaringKitty",
    hue: 249,
  },
  {
    id: "6S8Gez",
    name: "nyhrox",
    ticker: "NYHROX",
    wallet: "6S8GezkxYUfZy9JPtYnanbcZTMB87Wjt1qx3c6ELajKC",
    image: "https://unavatar.io/x/nyhrox",
    x: "https://x.com/nyhrox",
    handle: "@nyhrox",
    hue: 94,
  },
  {
    id: "7g5CJ7",
    name: "bestcook",
    ticker: "BESTCO",
    wallet: "7g5CJ754NboeY6D44MDdGwQmVX4Fvu59Q47c9ZKLPMkE",
    image:
      "https://socialimages.pump.fun/profile-images/7g5CJ754NboeY6D44MDdGwQmVX4Fvu59Q47c9ZKLPMkE/1c766d82-8964-4421-9fcf-3f6b3dc2ef5e",
    x: "",
    handle: "@bestcook",
    hue: 189,
  },
  {
    id: "4yb93X",
    name: "aki11a",
    ticker: "AKI11A",
    wallet: "4yb93XcR5FgV2WLDCpYo3hQYDBsnheSV3rGtvP54jXvk",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Green~Body-3-Green-wand~Face-1~Glasses-black~Winter-Hat-Yellow~Bracelet-green~Bowtie-Red.webp",
    x: "",
    handle: "@aki11a",
    hue: 62,
  },
  {
    id: "HaWhpx",
    name: "ebbecooks",
    ticker: "EBBECO",
    wallet: "HaWhpxyf8xw4YMogchnsiLGYE8MiAkybXbfWMJEnDwV6",
    image: "https://unavatar.io/x/ebbecooks",
    x: "https://x.com/ebbecooks",
    handle: "@ebbecooks",
    hue: 21,
  },
  {
    id: "8gYj3J",
    name: "FlamantRose",
    ticker: "FLAMAN",
    wallet: "8gYj3Jk1Ck9LJg9HQanrdzsmjL1ooM8cTqMe7TtgXfe",
    image:
      "https://socialimages.pump.fun/profile-images/8gYj3Jk1Ck9LJg9HQanrdzsmjL1ooM8cTqMe7TtgXfe/ed28683c-e1c2-4817-96a2-18340447bff1",
    x: "",
    handle: "@FlamantRose",
    hue: 265,
  },
  {
    id: "DAfhY1",
    name: "InkTidalVisitor",
    ticker: "INKTID",
    wallet: "DAfhY1YHLpWtDu8HzW5uH359tFMNfUUrXVLCdVRKBTLC",
    image: "",
    x: "",
    handle: "@InkTidalVisitor",
    hue: 124,
  },
  {
    id: "3neNZ7",
    name: "xSickFish",
    ticker: "XSICKF",
    wallet: "3neNZ7NxWhp5R92doeKkhoau8p7zVBtLQJzVrPXqsWEc",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Emerald~Body-Yellow~Face-4~Glasses-brown~Chef_s-Hat~Bracelet-green~Winter-Scarf.webp",
    x: "",
    handle: "@xSickFish",
    hue: 248,
  },
  {
    id: "8ZN71X",
    name: "NATE9169",
    ticker: "NATE91",
    wallet: "8ZN71XTdVo8yRovnGLmNgW3Tgniw6A4J3JGLvPD686FP",
    image: "https://unavatar.io/x/NATE9169",
    x: "https://x.com/NATE9169",
    handle: "@NATE9169",
    hue: 78,
  },
  {
    id: "88y4qU",
    name: "Bizzinness",
    ticker: "BIZZIN",
    wallet: "88y4qUChRATKVbjXDs5KRwfyaqE9n3onzCsDFCgTmGQr",
    image:
      "https://socialimages.pump.fun/profile-images/bf222a32-9abd-41c8-ac54-b7078c5f6740/8d706be4-6db9-4d6c-adb5-18bb27c12db2",
    x: "",
    handle: "@Bizzinness",
    hue: 232,
  },
  {
    id: "41xvyT",
    name: "croccapital",
    ticker: "CROCCA",
    wallet: "41xvyT53tY5RWGw5yM1Wb8fs3YkD6chusmXprMvKs2P2",
    image: "https://unavatar.io/x/croceatchart",
    x: "https://x.com/croceatchart",
    handle: "@croceatchart",
    hue: 245,
  },
  {
    id: "9BKsW5",
    name: "travisbickle",
    ticker: "TRAVIS",
    wallet: "9BKsW5UtV4dPzzdeC9M2MmGdHrA8jH1EZo5jzXkXciPP",
    image: "https://unavatar.io/x/travisbickle0x",
    x: "https://x.com/travisbickle0x",
    handle: "@travisbickle0x",
    hue: 247,
  },
  {
    id: "CyaE1V",
    name: "cented69420",
    ticker: "CENTED",
    wallet: "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o",
    image: "https://unavatar.io/x/Cented7",
    x: "https://x.com/Cented7",
    handle: "@Cented7",
    hue: 261,
  },
  {
    id: "B1ZMAR",
    name: "lastunknown",
    ticker: "LASTUN",
    wallet: "B1ZMARC6qhJYJrvBJywUYdtf6hq2WBkTgvbbnGuQsQnX",
    image: "https://unavatar.io/x/cparkerz42913",
    x: "https://x.com/cparkerz42913",
    handle: "@cparkerz42913",
    hue: 333,
  },
  {
    id: "A2JxRh",
    name: "cryptoaeon",
    ticker: "CRYPTO2",
    wallet: "A2JxRhVpS84UUWfKfCAJ84anexKzKdfDoh9tq5sdRPzH",
    image:
      "https://socialimages.pump.fun/profile-images/A2JxRhVpS84UUWfKfCAJ84anexKzKdfDoh9tq5sdRPzH/a594c866-2141-421e-be55-53a7cfe14c44",
    x: "",
    handle: "@cryptoaeon",
    hue: 49,
  },
  {
    id: "9Za4f5",
    name: "platothegato",
    ticker: "PLATOT",
    wallet: "9Za4f5sTCpkVbcg1du4WWYr9mimethehzHDyykWJhDr3",
    image: "https://unavatar.io/x/mikasa_yaegar",
    x: "https://x.com/mikasa_yaegar",
    handle: "@mikasa_yaegar",
    hue: 132,
  },
  {
    id: "6qudAN",
    name: "thedetective",
    ticker: "THEDET",
    wallet: "6qudAN2kV8mtCcYJxb5QQ6Vr15itdHHdeVbYm99NKMhy",
    image: "https://unavatar.io/x/MemeRetire",
    x: "https://x.com/MemeRetire",
    handle: "@MemeRetire",
    hue: 36,
  },
  {
    id: "pXGQ6J",
    name: "daddychilllll",
    ticker: "DADDYC",
    wallet: "pXGQ6J2ziRCvmYSLTT55FASf2jSHeCD6gju5xka31yV",
    image:
      "https://socialimages.pump.fun/profile-images/pXGQ6J2ziRCvmYSLTT55FASf2jSHeCD6gju5xka31yV/feb8eda8-a1da-48fd-9cf5-4d33349a0761.gif",
    x: "",
    handle: "@daddychilllll",
    hue: 76,
  },
  {
    id: "AQ46kf",
    name: "Yug1_tm",
    ticker: "YUG1TM",
    wallet: "AQ46kfYT3hW28Xg5gWHrJkzFSz1oGWBHC3FsTbqgMEco",
    image: "https://unavatar.io/x/Yug1_tm1",
    x: "https://x.com/Yug1_tm1",
    handle: "@Yug1_tm1",
    hue: 93,
  },
  {
    id: "ACTbvb",
    name: "slidrrz",
    ticker: "SLIDRR",
    wallet: "ACTbvbNm5qTLuofNRPxFPMtHAAtdH1CtzhCZatYHy831",
    image:
      "https://pump.mypinata.cloud/ipfs/bafkreibevpyy73foilrnjbcgptuv7wr3bn4x5diuyrwgzvbcedczt6s42a",
    x: "",
    handle: "@slidrrz",
    hue: 52,
  },
  {
    id: "EsWPRA",
    name: "Wolfie_On_Sol",
    ticker: "WOLFIE",
    wallet: "EsWPRA4dhxJ7eQmmt3Ti7J2sNk9E6y3KibCVw7DpYEpz",
    image: "https://unavatar.io/x/WolfieOnSol",
    x: "https://x.com/WolfieOnSol",
    handle: "@WolfieOnSol",
    hue: 17,
  },
  {
    id: "Ew58rp",
    name: "turbolobstersix",
    ticker: "TURBOL",
    wallet: "Ew58rptSs81EDh1BCGzdbuZjmowfADzHgf4cNKrgoeNP",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Emerald~Body-3-Green~Face-7~Empty+2~Durag-Yellow~Bracelet-orange~Winter-Scarf-Green.webp",
    x: "",
    handle: "@turbolobstersix",
    hue: 243,
  },
  {
    id: "6Aeqrh",
    name: "bobdotjpg",
    ticker: "BOBDOT",
    wallet: "6AeqrhqsmUtRE1V1FQvwetjCFFnXazqZLM9PUrzPLiGy",
    image: "https://unavatar.io/x/bobdotjpg",
    x: "https://x.com/bobdotjpg",
    handle: "@bobdotjpg",
    hue: 246,
  },
  {
    id: "77n6X7",
    name: "asaprubi",
    ticker: "ASAPRU",
    wallet: "77n6X7LtGy5AZprsvjZu1eaekJpxqLeVRZLPJZdBYyg9",
    image: "https://unavatar.io/x/zRubizz",
    x: "https://x.com/zRubizz",
    handle: "@zRubizz",
    hue: 106,
  },
  {
    id: "49fAsU",
    name: "Agent69420",
    ticker: "AGENT6",
    wallet: "49fAsUF3Nk8qbfpSrQND2sULKXanemwibYLGk5Jpn9bY",
    image: "https://unavatar.io/x/Agent69420",
    x: "https://x.com/Agent69420",
    handle: "@Agent69420",
    hue: 281,
  },
  {
    id: "FFdBLY",
    name: "alphaprophet",
    ticker: "ALPHAP",
    wallet: "FFdBLYqL9rs5fUT38ArE8GV2L3BziEgG5LJUu6sshfkF",
    image:
      "https://socialimages.pump.fun/profile-images/FFdBLYqL9rs5fUT38ArE8GV2L3BziEgG5LJUu6sshfkF/709f81af-4c45-4c6a-848f-67a6b02367ac",
    x: "",
    handle: "@alphaprophet",
    hue: 53,
  },
  {
    id: "DXbZug",
    name: "boapranois",
    ticker: "BOAPRA",
    wallet: "DXbZugG3hkX6o2cbNuKnUtDTQdjRRUx9uvtoE9FQCc3i",
    image:
      "https://socialimages.pump.fun/profile-images/DXbZugG3hkX6o2cbNuKnUtDTQdjRRUx9uvtoE9FQCc3i/7ee66341-23e1-459b-ab5e-1287501b6976",
    x: "",
    handle: "@boapranois",
    hue: 214,
  },
  {
    id: "FhooA6",
    name: "fohqu",
    ticker: "FOHQU",
    wallet: "FhooA6decuFN6kY8hiJZpD5gVz1tFszJSPnXWNkT4KfH",
    image:
      "https://socialimages.pump.fun/profile-images/0de70f32-fb6e-43e4-bd35-52a4a8559723/7e7026ef-8430-4441-85b8-1779ca13a419",
    x: "",
    handle: "@fohqu",
    hue: 57,
  },
  {
    id: "GccvEc",
    name: "SoloFNF",
    ticker: "SOLOFN",
    wallet: "GccvEcZqMrcNdp3CarCasGdN5dUfdQ4wZ6iQsk5myRzX",
    image: "https://unavatar.io/x/SoloFNF",
    x: "https://x.com/SoloFNF",
    handle: "@SoloFNF",
    hue: 24,
  },
  {
    id: "2k1cUV",
    name: "WTDD_jp",
    ticker: "WTDDJP",
    wallet: "2k1cUVB6SEpwKNYz2QSamLk5DT6Vq11nGyV2BMa3jaCf",
    image:
      "https://socialimages.pump.fun/profile-images/1acbe19a-b577-4534-9b6d-c0d5f87b4d71/609e2d28-bce3-4e17-9550-5601fa0dc6de",
    x: "",
    handle: "@WTDD_jp",
    hue: 213,
  },
  {
    id: "CAvvAF",
    name: "binaryshark2861",
    ticker: "BINARY",
    wallet: "CAvvAFNRfXDWTTDqwgxb9qSyYT8fTuTXWSFwL7Jsz8vT",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Blue~Body-3-Cyan-glass~Face-11~Glasses~Hairstyle-1---Green~Bracelet-orange~Winter-Scarf.webp",
    x: "",
    handle: "@binaryshark2861",
    hue: 244,
  },
  {
    id: "78N177",
    name: "sheep",
    ticker: "SHEEP",
    wallet: "78N177fzNJpp8pG49xDv1efYcTMSzo9tPTKEA9mAVkh2",
    image: "https://unavatar.io/x/imsheepsol",
    x: "https://x.com/imsheepsol",
    handle: "@imsheepsol",
    hue: 193,
  },
  {
    id: "GKMUxp",
    name: "edonfx",
    ticker: "EDONFX",
    wallet: "GKMUxpHS5uoW1dqjxzyJP66bHC3GbsKaQKU1tzXmzReb",
    image: "https://unavatar.io/x/edonfx",
    x: "https://x.com/edonfx",
    handle: "@edonfx",
    hue: 28,
  },
  {
    id: "2omVC1",
    name: "itsmigglsol",
    ticker: "ITSMIG",
    wallet: "2omVC16AduiQQZn36yF5pwZtRJ7UQrtmuiriEpD5YTir",
    image: "https://unavatar.io/x/miggl_sol",
    x: "https://x.com/miggl_sol",
    handle: "@miggl_sol",
    hue: 252,
  },
  {
    id: "mmJDE8",
    name: "mmjde8",
    ticker: "MMJDE8",
    wallet: "mmJDE8zc2BGQmTakxe3SYmZaMbEdR63rLCdDNa3qmnF",
    image:
      "https://socialimages.pump.fun/profile-images/b4ecdf59-2127-4595-b455-4cc70509c1aa/33691716c85cbce28d8ca00bd8569ea5",
    x: "",
    handle: "@mmjde8",
    hue: 5,
  },
  {
    id: "Bi4rd5",
    name: "theonomics",
    ticker: "THEONO",
    wallet: "Bi4rd5FH5bYEN8scZ7wevxNZyNmKHdaBcvewdPFxYdLt",
    image:
      "https://socialimages.pump.fun/profile-images/ba5a6e37-1bfe-4f79-82da-03f23e38d630/5410f3ff-b17f-4f31-97b8-a473b85580d2",
    x: "",
    handle: "@theonomics",
    hue: 66,
  },
  {
    id: "BNnN2M",
    name: "Bob_Benson",
    ticker: "BOBBEN",
    wallet: "BNnN2MqfWLvgThYBsv6v8JQaYZXYKYahC5YCy27Ct1cX",
    image:
      "https://pump.mypinata.cloud/ipfs/bafkreiewgbud2zfxluhaa7iskanlzbf7aeq4sjgeutovuqet4vt2s5bfqi",
    x: "",
    handle: "@Bob_Benson",
    hue: 126,
  },
  {
    id: "HWaKJX",
    name: "s0rry",
    ticker: "S0RRY",
    wallet: "HWaKJXeHTBRn9r1tQFcGSf1Z7o4iExYyrvyMTwYgseXF",
    image: "https://unavatar.io/x/s0rry_sms",
    x: "https://x.com/s0rry_sms",
    handle: "@s0rry_sms",
    hue: 70,
  },
  {
    id: "EgYa22",
    name: "Uncquant",
    ticker: "UNCQUA",
    wallet: "EgYa22bNrcQGRJny4rGJz8eJe5CSFKtXEqB9qPQQGN9p",
    image:
      "https://socialimages.pump.fun/profile-images/e4f33841-f16f-48ee-8cf8-d586a111e3d2/418925de-68ad-4548-9616-79393a20f23e",
    x: "",
    handle: "@Uncquant",
    hue: 261,
  },
  {
    id: "J8kNsf",
    name: "HeadGlitch",
    ticker: "HEADGL",
    wallet: "J8kNsftBvQ5akQeKHUPbm7mwQ4ASjmE5BJNa4riNjs5k",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Emerald~Body-3-Red-glass~Face-10~Empty~Hat~Bracelet-green~Scarf-Green.webp",
    x: "",
    handle: "@HeadGlitch",
    hue: 157,
  },
  {
    id: "CAPn1y",
    name: "cap",
    ticker: "CAP",
    wallet: "CAPn1yH4oSywsxGU456jfgTrSSUidf9jgeAnHceNUJdw",
    image: "https://unavatar.io/x/cap100x",
    x: "https://x.com/cap100x",
    handle: "@cap100x",
    hue: 127,
  },
  {
    id: "Be24Gb",
    name: "chairman",
    ticker: "CHAIRM",
    wallet: "Be24Gbf5KisDk1LcWWZsBn8dvB816By7YzYF5zWZnRR6",
    image: "https://unavatar.io/x/Chairman_DN",
    x: "https://x.com/Chairman_DN",
    handle: "@Chairman_DN",
    hue: 273,
  },
  {
    id: "EqiFgy",
    name: "banval",
    ticker: "BANVAL",
    wallet: "EqiFgyNw6kgrmYstWyrP8VjKhka7XEmKTZzHSmwpr1Zb",
    image: "https://unavatar.io/x/Ban_Val",
    x: "https://x.com/Ban_Val",
    handle: "@Ban_Val",
    hue: 106,
  },
  {
    id: "BAk7jy",
    name: "xavierrrrrr",
    ticker: "XAVIER",
    wallet: "BAk7jy4pPS9u4tBsbGWVJstrbami8UuxQtRktVFnfx9k",
    image:
      "https://socialimages.pump.fun/profile-images/8ed49b6d-c5f0-4126-842d-06b1540f6399/898f418c-4d60-43f2-9131-b4afa60b7d06",
    x: "",
    handle: "@xavierrrrrr",
    hue: 142,
  },
  {
    id: "H31vEB",
    name: "megga",
    ticker: "MEGGA",
    wallet: "H31vEBxSJk1nQdUN11qZgZyhScyShhscKhvhZZU3dQoU",
    image: "https://unavatar.io/x/Megga",
    x: "https://x.com/Megga",
    handle: "@Megga",
    hue: 303,
  },
  {
    id: "jmemeh",
    name: "itzmemewitz",
    ticker: "ITZMEM",
    wallet: "jmemehQbZXX7QqNE7Eyi81MdTZw6cEAT6TU4Kinwtru",
    image: "https://unavatar.io/x/itzmemewitz",
    x: "https://x.com/itzmemewitz",
    handle: "@itzmemewitz",
    hue: 168,
  },
  {
    id: "62qEWU",
    name: "sl0wie",
    ticker: "SL0WIE",
    wallet: "62qEWURTpb8RNqoPCrjaoRcfU4PneigVKbiuGtin2Wb4",
    image: "https://unavatar.io/x/sl0wie",
    x: "https://x.com/sl0wie",
    handle: "@sl0wie",
    hue: 248,
  },
  {
    id: "FqamE7",
    name: "EustazZ",
    ticker: "EUSTAZ",
    wallet: "FqamE7xrahg7FEWoByrx1o8SeyHt44rpmE6ZQfT7zrve",
    image: "https://unavatar.io/x/Eustazzeus",
    x: "https://x.com/Eustazzeus",
    handle: "@Eustazzeus",
    hue: 72,
  },
  {
    id: "Fpf2DJ",
    name: "kainrtd",
    ticker: "KAINRT",
    wallet: "Fpf2DJPM3n7LB9RWKaZ2zQ3KRcVWACHXpjngBNS99Q2H",
    image:
      "https://socialimages.pump.fun/profile-images/Fpf2DJPM3n7LB9RWKaZ2zQ3KRcVWACHXpjngBNS99Q2H/627f0ca4-e830-401f-89c1-85f0b6189700",
    x: "",
    handle: "@kainrtd",
    hue: 329,
  },
  {
    id: "FhwFLN",
    name: "FaZeBlaze",
    ticker: "FAZEBL",
    wallet: "FhwFLN5EtYtuUHmetiVxNCBd1tEitFvWwQq1XyizaYMA",
    image: "https://unavatar.io/x/FaZeBlaze",
    x: "https://x.com/FaZeBlaze",
    handle: "@FaZeBlaze",
    hue: 108,
  },
  {
    id: "FdSShB",
    name: "element69420",
    ticker: "ELEMEN",
    wallet: "FdSShBiR1nBtxQzhwNMszyRdcvMVLiAeVraJLvERERZL",
    image: "https://unavatar.io/x/Element69420",
    x: "https://x.com/Element69420",
    handle: "@Element69420",
    hue: 45,
  },
  {
    id: "4y2T1g",
    name: "hdegroot",
    ticker: "HDEGRO",
    wallet: "4y2T1ghykCTq4EddoXjptZamk4qAsqcZw6eKxS8jdvE1",
    image: "https://unavatar.io/x/hdegrootvan",
    x: "https://x.com/hdegrootvan",
    handle: "@hdegrootvan",
    hue: 139,
  },
  {
    id: "ApSdbn",
    name: "skayfe",
    ticker: "SKAYFE",
    wallet: "ApSdbn9G4EvLgpLhmvvMT24yaqb38fWG2Ub1ZEqD6Jtu",
    image: "https://unavatar.io/x/skayle00",
    x: "https://x.com/skayle00",
    handle: "@skayle00",
    hue: 13,
  },
  {
    id: "5pUgxQ",
    name: "jamal",
    ticker: "JAMAL",
    wallet: "5pUgxQGgX36GyV5BdsBNRAw9JxJ6Br4UVddJmJ3sumhc",
    image: "https://unavatar.io/x/whoisjamal1337",
    x: "https://x.com/whoisjamal1337",
    handle: "@whoisjamal1337",
    hue: 207,
  },
  {
    id: "4pXEMv",
    name: "BillySparks",
    ticker: "BILLYS",
    wallet: "4pXEMvvgUZdhukWYyCE9L4XQzw4bvHRtQug3T1ao7Xfk",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Emerald~Body-2-Red~Face-2~Empty+2~Hairstyle-3~Bracelet-orange~Bowtie-Orange.webp",
    x: "",
    handle: "@BillySparks",
    hue: 171,
  },
  {
    id: "tBVFi3",
    name: "newevo",
    ticker: "NEWEVO",
    wallet: "tBVFi3uhRxDtn4C5Sxy7D6yUQ2qUfp2qkjcoL6ttmFt",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Pink~Body-3-Blue-wand~Face-11~Sunglasses~Cap-Green~Bracelet-green~Scarf-Green.webp",
    x: "",
    handle: "@newevo",
    hue: 6,
  },
  {
    id: "387FRw",
    name: "sh4vwty",
    ticker: "SH4VWT",
    wallet: "387FRwow6MKDhSwuMULhKjqeXuxoBY4BbbaSntdk9LaH",
    image: "https://unavatar.io/x/sh4vwty",
    x: "https://x.com/sh4vwty",
    handle: "@sh4vwty",
    hue: 347,
  },
  {
    id: "3P3Tr5",
    name: "coreyape",
    ticker: "COREYA",
    wallet: "3P3Tr5HErnSSqmNrjGXBaACxQj3NmKfi3Efbu5FuuY7i",
    image: "https://unavatar.io/x/Corey_Ape",
    x: "https://x.com/Corey_Ape",
    handle: "@Corey_Ape",
    hue: 358,
  },
  {
    id: "K6Eh9f",
    name: "SolLovingFork",
    ticker: "SOLLOV",
    wallet: "K6Eh9fwKkrhVNq6SpRtJn7F4Myi3HUst5QP8x5BKHnR",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Cyan~Body-3-Cyan-glass~Face-8~Sunglasses~Cap-back-red~Watch~Bowtie-Indigo.webp",
    x: "",
    handle: "@SolLovingFork",
    hue: 235,
  },
  {
    id: "2Ev9Dk",
    name: "leantuna23013",
    ticker: "LEANTU",
    wallet: "2Ev9DkLKUpQn1Vapq9CamNTGFXcMHp9aMzYDQGUR6RXe",
    image:
      "https://socialimages.pump.fun/profile-images/2Ev9DkLKUpQn1Vapq9CamNTGFXcMHp9aMzYDQGUR6RXe/49f3c9b8-5a1e-4d17-ac52-76bc42c769b5",
    x: "",
    handle: "@leantuna23013",
    hue: 10,
  },
  {
    id: "CkZqyu",
    name: "swansonbenson0",
    ticker: "SWANSO",
    wallet: "CkZqyugfNYUpCEfRTeERprSTwLPc6rcrtUNcdDZEig53",
    image: "https://unavatar.io/x/swansonbenson0",
    x: "https://x.com/swansonbenson0",
    handle: "@swansonbenson0",
    hue: 15,
  },
  {
    id: "F2dWzX",
    name: "feistysquid8768",
    ticker: "FEISTY",
    wallet: "F2dWzXQ5yBXqGEUx4EnJC9iZhU9gh9FF8UiugE9pmDTa",
    image:
      "https://socialimages.pump.fun/profile-images/pumpatar/2/Orange~Body-3-Indigo-wand~Face-6~Sunglasses~Headphones-Grey~Bracelet-orange~Tie-Red.webp",
    x: "",
    handle: "@feistysquid8768",
    hue: 150,
  },
  {
    id: "CKB1XY",
    name: "Dolo",
    ticker: "DOLO",
    wallet: "CKB1XYgbEmfEE3FJev7gFwEVtoqEvmsX6GhnbuFvuN5d",
    image: "https://unavatar.io/x/doloxbt",
    x: "https://x.com/doloxbt",
    handle: "@doloxbt",
    hue: 28,
  },
  {
    id: "45oN2t",
    name: "Royalchestnut",
    ticker: "ROYALC",
    wallet: "45oN2tCsfzG325wEPnJPvMYpuY2tgASYHmgRPdnMZB5a",
    image:
      "https://socialimages.pump.fun/profile-images/49f76c36-d065-4dc4-a372-5aa6fd1692c9/c2b550bc-5e0b-4bb3-b98c-1761c3c92aa8",
    x: "",
    handle: "@Royalchestnut",
    hue: 170,
  },
  {
    id: "3kDGnC",
    name: "_smokey",
    ticker: "SMOKEY",
    wallet: "3kDGnCvAmUF3EjdbMkF42ocL1SStNDKxaUNPA1WpRf5z",
    image:
      "https://socialimages.pump.fun/profile-images/196f955c-be67-44dd-9bbf-c1396bb420d6/3c6ec95d-4e0b-4966-aeaa-79a0936a0b18",
    x: "",
    handle: "@_smokey",
    hue: 131,
  },
  {
    id: "9nqrQs",
    name: "blackjackman",
    ticker: "BLACKJ",
    wallet: "9nqrQsdz6P15EmfpbZ4kpruS46y4wUkwRBSgdcqqxMrj",
    image:
      "https://socialimages.pump.fun/profile-images/4cc3c3dc-041d-4f18-ad8a-403aa821e15f/b6ff10349fb37f6db09a9e532d3db349",
    x: "",
    handle: "@blackjackman",
    hue: 108,
  },
  {
    id: "zhYnXq",
    name: "onlyzhynx",
    ticker: "ONLYZH",
    wallet: "zhYnXqK3MNSmwS3yxSvPmY5kUa1n2WUaCJgYUDrAHkL",
    image: "https://unavatar.io/x/onlyzhynx",
    x: "https://x.com/onlyzhynx",
    handle: "@onlyzhynx",
    hue: 32,
  },
  {
    id: "2CFywH",
    name: "otsu",
    ticker: "OTSU",
    wallet: "2CFywHXDPjDK2iRQsb95vnjgncDUZeQKJ6MceJ4ALpdc",
    image:
      "https://socialimages.pump.fun/profile-images/e134882e-f6c8-4e19-bab4-15933cbce69e/4300593d-29a8-49e8-a005-d6377aa5f7a2",
    x: "",
    handle: "@otsu",
    hue: 274,
  },
  {
    id: "98jY7C",
    name: "polakmaly",
    ticker: "POLAKM",
    wallet: "98jY7CtRKsMMXMHVpvDQh1K5kFzM3HM4DVqjPAyYLdvT",
    image: "https://pump.mypinata.cloud/ipfs/QmXwbSF1Uut7wgHBcEp6xgFYyvVatNUMmZyN94Mi6bE5Qd",
    x: "",
    handle: "@polakmaly",
    hue: 149,
  },
  {
    id: "DVv4B2",
    name: "teezee",
    ticker: "TEEZEE",
    wallet: "DVv4B2KKdkx84zpk8viAf6qo9c57pNPwg8wf4VMnj8Ly",
    image: "https://unavatar.io/x/0xtuzi",
    x: "https://x.com/0xtuzi",
    handle: "@0xtuzi",
    hue: 267,
  },
  {
    id: "GRWXXW",
    name: "TheSurveillor",
    ticker: "THESUR",
    wallet: "GRWXXWeQhKQYHR3BCpkCHtDAXmTej5Cwb2tYPM6uV5WP",
    image: "https://unavatar.io/x/surveillor",
    x: "https://x.com/surveillor",
    handle: "@surveillor",
    hue: 63,
  },
  {
    id: "FH8xnC",
    name: "dweedify",
    ticker: "DWEEDI",
    wallet: "FH8xnCwgoQgk3nXuePEdxYB5SZDTWSZav27smVcHjN1q",
    image: "https://unavatar.io/x/imnoctus",
    x: "https://x.com/imnoctus",
    handle: "@imnoctus",
    hue: 55,
  },
];

export const KOLS: Kol[] = SEEDS.map((s) => ({
  id: s.id,
  // Empty when the trader has no linked social — deliberately NOT falling back
  // to a truncated wallet. The wallet is already rendered next to this (and,
  // for unnamed traders, is the display name too), so a fallback here printed
  // the same address three times in a row on the listing page.
  handle: s.handle,
  name: s.name,
  ticker: s.ticker,
  wallet: s.wallet,
  image: s.image,
  x: s.x,
  avatar: `linear-gradient(135deg, oklch(0.72 0.19 ${s.hue}), oklch(0.42 0.13 ${(s.hue + 60) % 360}))`,
  price: 0,
  change24h: 0,
  marketCap: 0,
  volume24h: 0,
  holders: 0,
  winRate: 0,
  pnl30d: 0,
  trades30d: 0,
  avgHold: "n/a",
  chain: "Solana",
  bio: `Solana trader tracked from wallet ${s.wallet.slice(0, 4)}...${s.wallet.slice(-4)}. Listing opens at 0.0001 SOL; share price moves with the trader's live on-chain performance since launch.`,
}));

export function getKol(id: string) {
  return KOLS.find((k) => k.id === id);
}

export function shortWallet(w: string) {
  return `${w.slice(0, 6)}...${w.slice(-4)}`;
}

export function perfScore(k: Kol) {
  return Math.round(
    k.winRate * 6 + k.change24h * 3 + (k.pnl30d / 1_000_000) * 42 + k.trades30d / 40,
  );
}

/**
 * USD, with enough precision to still mean something below a cent.
 *
 * Share prices here are cents, not dollars — a listing trades around $0.0125.
 * At a fixed two decimals every one of the 108 listings rendered as "$0.01",
 * so the price column could not distinguish a $0.0096 trader from a $0.0125
 * one, and the board looked identical top to bottom.
 *
 * Worse in the fills list, where the same rounding turned a real round trip
 * into an apparent catastrophe: buying at $0.0125 displayed as $0.02 and
 * selling at $0.0120 displayed as $0.01, so a 4% fee cost read as losing half
 * the position. That is the kind of number that makes someone think the app
 * stole from them.
 *
 * So precision scales with magnitude: normal money keeps two decimals, and
 * small values get enough digits to stay distinguishable. Pass `digits`
 * explicitly to force a fixed width where columns must align.
 */
/**
 * A formatter must never be the reason a page fails to render.
 *
 * These called .toLocaleString() and .toFixed() straight on the argument, so
 * undefined or null threw a TypeError — and a TypeError thrown during render
 * takes out the whole React tree, not just the number. A missing price is a
 * gap in the data; a white screen is an outage, and turning the first into the
 * second is the wrong trade at every point on a live market page.
 *
 * TypeScript says these are numbers, which is true of every call site today.
 * It is not true of what arrives at runtime from a feed row, a chain read that
 * failed, or a listing that has no price yet — all of which exist here.
 *
 * A dash for anything that is not a finite number. It reads as "no value",
 * which is what it is, and it matches how the splash chips report the same
 * absence.
 */
export const fmtUsd = (n: number, digits?: number) => {
  if (!Number.isFinite(n)) return "—";
  const abs = Math.abs(n);
  const d = digits ?? (abs === 0 ? 2 : abs >= 1 ? 2 : abs >= 0.001 ? 4 : abs >= 0.00001 ? 6 : 8);
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: d,
    maximumFractionDigits: d,
  });
};

export function fmtCompact(n: number) {
  // Same reasoning as fmtUsd: never render "$NaN" or "$InfinityB", both of
  // which this produced. A dash is the honest output for a number that is not
  // one.
  if (!Number.isFinite(n)) return "—";
  const abs = Math.abs(n);
  const sign = n < 0 ? "-" : "";
  if (abs >= 1e9) return `${sign}$${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${sign}$${(abs / 1e6).toFixed(2)}M`;
  if (abs >= 1e3) return `${sign}$${(abs / 1e3).toFixed(1)}K`;
  return `${sign}$${abs.toFixed(0)}`;
}

export const fmtPct = (n: number) => {
  if (!Number.isFinite(n)) return "—";
  return `${n >= 0 ? "+" : ""}${n.toFixed(2)}%`;
};
