/**
 * gen-lut-evm.ts — generates the on-chain score->price lookup table for the
 * Robinhood Chain (EVM) port of the sharps program.
 * ----------------------------------------------------------------
 * Mirrors oracle/gen-lut.ts exactly, but targets wei instead of lamports.
 * Solidity has no floating-point either, so this is the same fix: a
 * 101-entry constant array (one per integer score 0..100), byte-exact
 * against this repo's own reference formula (oracle/score.ts), instead of
 * runtime float math on-chain.
 *
 * BASE_PRICE_WEI is chosen to land near $0.01 at a rough $2,500/ETH — the
 * same kind of static approximation the Solana build already uses for
 * SOL_PRICE_USD (see src/lib/market-store.tsx), not a live price feed.
 * Revisit both together if/when a real ETH/USD feed is wired in.
 *
 * Run:
 *   npx tsx oracle/gen-lut-evm.ts > evm/src/lib/ScoreLut.sol
 */

import { scoreToAnchor, BASE_PRICE } from "./score.js";

/** Wei per BASE_PRICE (0.001 "SOL-equivalent" unit) of scoreToAnchor's output. */
const BASE_PRICE_WEI = 4_000_000_000_000n; // 0.000004 ETH ≈ $0.01 @ $2,500/ETH

function main() {
  const values: bigint[] = [];
  for (let score = 0; score <= 100; score++) {
    const anchor = scoreToAnchor(score); // in the same units as BASE_PRICE (0.001-based)
    const scaled = (anchor / BASE_PRICE) * Number(BASE_PRICE_WEI);
    const wei = BigInt(Math.round(scaled));
    if (wei <= 0n) {
      throw new Error(`scoreToAnchor(${score}) produced a non-positive wei value: ${wei}`);
    }
    values.push(wei);
  }

  const lines: string[] = [];
  lines.push("// SPDX-License-Identifier: MIT");
  lines.push("pragma solidity ^0.8.24;");
  lines.push("");
  lines.push("// AUTO-GENERATED by oracle/gen-lut-evm.ts — DO NOT EDIT BY HAND.");
  lines.push("// Regenerate with: npx tsx oracle/gen-lut-evm.ts > evm/src/lib/ScoreLut.sol");
  lines.push("// Values are scoreToAnchor(score) from oracle/score.ts, rescaled to wei, for score = 0..100.");
  lines.push("");
  lines.push("library ScoreLut {");
  lines.push("    /// score (0..=100) -> price in wei, byte-exact with oracle/score.ts::scoreToAnchor");
  lines.push("    /// (rescaled from SOL-lamport units to wei via gen-lut-evm.ts's BASE_PRICE_WEI).");
  lines.push("    function priceForScore(uint8 score) internal pure returns (uint256) {");
  lines.push("        require(score <= 100, \"score>100\");");
  lines.push("        uint256[101] memory lut = [");
  for (let i = 0; i < values.length; i += 5) {
    const chunk = values
      .slice(i, i + 5)
      .map((v) => `uint256(${v.toString()})`)
      .join(", ");
    const suffix = i + 5 < values.length ? "," : "";
    lines.push(`            ${chunk}${suffix}`);
  }
  lines.push("        ];");
  lines.push("        return lut[score];");
  lines.push("    }");
  lines.push("}");
  lines.push("");

  process.stdout.write(lines.join("\n") + "\n");
}

main();
