/**
 * gen-lut.ts — generates the on-chain score->price lookup table.
 * ----------------------------------------------------------------
 * The Anchor program prices listings in lamports using a 101-entry constant
 * array (one entry per integer score 0..100) instead of runtime float math,
 * so on-chain price derivation has zero floating-point/determinism risk and
 * is byte-exact against this repo's own reference formula.
 *
 * `scoreToAnchor` (oracle/score.ts) is that reference formula — it's already
 * SOL-native (BASE_PRICE = 0.001 SOL), unlike oracle/pricing.ts's USD curve,
 * which is why the on-chain program is priced/settled in SOL and USD stays a
 * pure client-side display conversion.
 *
 * Run:
 *   npx tsx oracle/gen-lut.ts > anchor/programs/sharps/src/lut.rs
 *
 * Re-run and diff whenever oracle/score.ts's curve changes, to catch drift
 * between the TS reference and the committed Rust copy.
 */

import { scoreToAnchor } from "./score.js";

const LAMPORTS_PER_SOL = 1_000_000_000;

function main() {
  const values: bigint[] = [];
  for (let score = 0; score <= 100; score++) {
    const sol = scoreToAnchor(score);
    const lamports = Math.round(sol * LAMPORTS_PER_SOL);
    if (!Number.isFinite(lamports) || lamports <= 0) {
      throw new Error(`scoreToAnchor(${score}) produced a non-positive/non-finite lamport value: ${lamports}`);
    }
    values.push(BigInt(lamports));
  }

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by oracle/gen-lut.ts — DO NOT EDIT BY HAND.");
  lines.push("// Regenerate with: npx tsx oracle/gen-lut.ts > anchor/programs/sharps/src/lut.rs");
  lines.push("// Values are scoreToAnchor(score) from oracle/score.ts, in lamports, for score = 0..100.");
  lines.push("");
  lines.push("/// score (0..=100) -> price in lamports, byte-exact with oracle/score.ts::scoreToAnchor.");
  lines.push("pub const ANCHOR_LUT: [u64; 101] = [");
  for (let i = 0; i < values.length; i += 10) {
    const chunk = values.slice(i, i + 10).map((v) => `${v.toString()}u64`).join(", ");
    lines.push(`    ${chunk},`);
  }
  lines.push("];");
  lines.push("");

  process.stdout.write(lines.join("\n") + "\n");
}

main();
